name: mfrc522-coding-style

on:
  pull_request:
  push:
    branches:
      master

jobs:
  coding-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download checkpatch.pl
      run: |
        curl https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl -O
        chmod +x checkpatch.pl

    - name: Check the coding style
      run: ./checkpatch.pl --no-tree -f --ignore UNDOCUMENTED_DT_STRING module/*.[ch]
